sudo: required
services:
  - docker
before_install:
  - docker build -t mkawtharani/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run mkawtharani/react-test npm test -- --coverage
after_success
  - docker build -t mkawtharani/multi-client ./client
  - docker build -t mkawtharani/multi-nginx ./nginx
  - docker build -t mkawtharani/multi-server ./server
  - docker build -t mkawtharani/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push -t mkawtharani/multi-client
  - docker push -t mkawtharani/multi-nginx
  - docker push -t mkawtharani/multi-server
  - docker push -t mkawtharani/multi-worker

